typeset -U path
#path=($path /usr/local/bin /usr/local/opt/ruby/bin)
#PATH=$PATH:/Users/d3p425/bin:/usr/local/share/npm/bin:/Users/d3p425/src/Google/adt-bundle-mac-x86_64-20130514/sdk/platform-tools:/Users/d3p425/src/Google/adt-bundle-mac-x86_64-20130514/sdk/tools; export PATH

#PYTHONPATH=/usr/local/lib/python2.7/site-packages/; export PYTHONPATH

#The value of this variable describes what color to use for which attribute
#when colors are enabled with CLICOLOR.  This string is a concatenation of
#pairs of the format fb, where f is the foreground color and b is the
#background color. The color designators are as follows:
# a     black
# b     red
# c     green
# d     brown
# e     blue
# f     magenta
# g     cyan
# h     light grey
# A     bold black, usually shows up as dark grey
# B     bold red
# C     bold green
# D     bold brown, usually shows up as yellow
# E     bold blue
# F     bold magenta
# G     bold cyan
# H     bold light grey; looks like bright white
# x     default foreground or background
#
#Note that the above are standard ANSI colors.  The actual display may
#differ depending on the color capabilities of the terminal in use.
#The order of the attributes are as follows:
# 1.   directory
# 2.   symbolic link
# 3.   socket
# 4.   pipe
# 5.   executable
# 6.   block special
# 7.   character special
# 8.   executable with setuid bit set
# 9.   executable with setgid bit set
#
# Default Colors of LSCOLORS
# LSCOLORS = "exfxcxdxbxegedabagacad"
#         1122334455667788990011
